### ISSUE TITLE
UI clean up

### ISSUE THREAD

**Issue by kavi87** [seedstack/batch-monitoring-function#1]
- [x] Replace static NgGrid with bower managed UiGrid (upgrade it to last version in w20 btw)
- [x] Clean up css : try to replace custom style with Bootstrap style only
- [x] Change layout (remove panels)
- [x] Replace hard managed dependencies (d3.layout)
- [x] Add mock data for future refactoring

**Comment by adrienlauer** [comment]
@kavi87 For information ui-grid has been updated to the latest version (rc21) in W20 2.0.0 M2 release.
